### ISSUE TITLE
How to use in Ionic 3+

### ISSUE THREAD

**Issue by mmubasher** [opentok/opentok-network-test-js#93]
I request your help for how to use _opentok-network-test-js_  in Ionic 3+. I tried with following code 
```
import { Component, OnInit } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';
import NetworkTest from 'opentok-network-test-js';
import { TabsPage } from '../pages/tabs/tabs';
import { OT } from "opentok-network-test-js/dist/NetworkTest/types/opentok";

@Component({
  templateUrl: 'app.html'
})
export class MyApp implements OnInit {
  rootPage: any = TabsPage;
  otNetworkTest: NetworkTest;
  OT: OT.Client;

  constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen) {
    platform.ready()
      .then(() => {
        // Okay, so the platform is ready and our plugins are available.
        // Here you can do any higher level native things you might need.
        statusBar.styleDefault();
        splashScreen.hide();
      })
      .then(() => {
        this.otNetworkTest = new NetworkTest(this.OT, {
          apiKey: 'XXXXXXXXXXXXXXXXXX',
          sessionId: 'XXXXXXXXXXXXXXXXXX',
          token: 'XXXXXXXXXXXXXXXXXX'
        });
      });
  }

  ngOnInit() {
    this.otNetworkTest.testConnectivity().then((results) => {
      console.log('OpenTok connectivity test results', results);
    }).catch(function (error) {
      console.log('OpenTok connectivity test error', error);
    });
  }
}
```
However, on running with `npm start`, I get the following run-time error. Can you please tell me how to get around this or if I need a Cordova plugin for this.
```
Error: An instance of OT, the OpenTok.js client SDK, is required.
    at t (http://localhost:8100/build/vendor.js:123248:14079)
    at new t (http://localhost:8100/build/vendor.js:123248:14238)
    at e.value (http://localhost:8100/build/vendor.js:123248:27375)
    at new e (http://localhost:8100/build/vendor.js:123248:27110)
    at new MyApp (http://localhost:8100/build/main.js:297:30)
    at createClass (http://localhost:8100/build/vendor.js:12859:20)
    at createDirectiveInstance (http://localhost:8100/build/vendor.js:12700:37)
    at createViewNodes (http://localhost:8100/build/vendor.js:14158:53)
    at createRootView (http://localhost:8100/build/vendor.js:14047:5)
    at callWithDebugContext (http://localhost:8100/build/vendor.js:15472:42)
```
Diagnostics Platform Information
```
Ionic Framework: 3.9.2
Ionic App Scripts: 3.2.0
Angular Core: 5.2.11
Angular Compiler CLI: 5.2.11
Node: 10.13.0
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
```

**Comment by msach22** [comment]
@mmubasher Thanks for filing the issue. It looks like you're not passing in the OpenTok JS SDK to the `NetworkTest` constructor, can you please set `OT` to the OpenTok.js SDK? You can download the OpenTok JS SDK via npm by running the following: `npm install @opentok/client`?

**Comment by mmubasher** [comment]
@msach22  thanks for following up on this. I proceeded testing with @opentok/client and getting the errors 
```
Argument of type 'typeof OT' is not assignable to parameter of type 'Client'.
  Types of property 'checkScreenSharingCapability' are incompatible.
    Type '(callback: (response: OT.ScreenSharingCapabilityResponse) => void) => void' is not assignable to type '(callback: (response: OT.ScreenSharingCapabilityResponse) => void) => void'. Two different types with this name exist, but they are unrelated.
      Types of parameters 'callback' and 'callback' are incompatible.
        Types of parameters 'response' and 'response' are incompatible.
          Type 'OT.ScreenSharingCapabilityResponse' is not assignable to type 'OT.ScreenSharingCapabilityResponse'. Two different types with this name exist, but they are unrelated.
            Property 'extensionInstalled' is optional in type 'ScreenSharingCapabilityResponse' but required in type 'ScreenSharingCapabilityResponse'. 
```
In the constructor of NetworkTest, first param is an OT Client but @opentok/client does not provides that. It wont work

**Comment by msach22** [comment]
@mmubasher Can you please share the way you're instantiating the `NetworkTest` object? It should not be `OT.Client` - instead just use `OT` like so:

```
const otNetworkTest = new NetworkTest(OT, {
  apiKey: '123456', // Add the API key for your OpenTok project here.
  sessionId: '1_MX40NzIwMzJ-fjE1MDElGQkJJfn4', // Add a test session ID for that project
  token: 'T1==cGFydG5lcXN0PQ==' // Add a token for that session here
});
```

**Comment by mmubasher** [comment]
It gives a compile time error. I tried following code 
```
import { Component, OnInit } from '@angular/core';
import NetworkTest from 'opentok-network-test-js';
import * as OT from '@opentok/client';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage implements OnInit {
  otNetworkTest: NetworkTest;

  constructor() {
          this.otNetworkTest = new NetworkTest(OT, {
            apiKey: '460 ...',
            sessionId: '1_MX40NjA5OTM5Mn5-MTU0MjY ...',
            token: 'T1==cGFydG5lcl9pZD00NjA5OTM5MiZzaWc ...'
          });
  }

  ngOnInit() {
    this.otNetworkTest.testConnectivity().then((results) => {
      console.log('OpenTok connectivity test results', results);
    }).catch(function (error) {
      console.log('OpenTok connectivity test error', error);
    });
  }
}
```
but it still presents the same error 
```
Argument of type 'typeof OT' is not assignable to parameter of type 'Client'.
  Types of property 'checkScreenSharingCapability' are incompatible.
    Type '(callback: (response: OT.ScreenSharingCapabilityResponse) => void) => void' is not assignable to type '(callback: (response: OT.ScreenSharingCapabilityResponse) => void) => void'. Two different types with this name exist, but they are unrelated.
      Types of parameters 'callback' and 'callback' are incompatible.
        Types of parameters 'response' and 'response' are incompatible.
          Type 'OT.ScreenSharingCapabilityResponse' is not assignable to type 'OT.ScreenSharingCapabilityResponse'. Two different types with this name exist, but they are unrelated.
            Property 'extensionInstalled' is optional in type 'ScreenSharingCapabilityResponse' but required in type 'ScreenSharingCapabilityResponse'. 
```
One more thing I wanted to share is that even though if networkjs works how is it going to access camera and mic resources in Ionic platform? Would not I need some native code interaction for it?

**Comment by msach22** [comment]
@mmubasher Apologies for the delay. Quick question, are you running this for the web or mobile? Unfortunately, this network test does not support mobile endpoints (specifically if you're using Ionic with our Cordova plugin).

**Comment by mmubasher** [comment]
@msach22  thank you for your response. Yes you are right, I need to run it in a Cordova environment where camera is not accessible using browser kit. So, this means it needs to be implemented similar to the [opentok/cordova-plugin-opentok](https://github.com/opentok/cordova-plugin-opentok) right?

**Comment by msach22** [comment]
Yes, we would have to create a custom plugin for network test just like [opentok/cordova-plugin-opentok](https://github.com/opentok/cordova-plugin-opentok).

I'm going to go ahead and close the issue here, but please feel free to file an issue on the Cordova plugin so we can track it there.
